### ISSUE TITLE
Version 0.4.0

### ISSUE THREAD

**Issue by VictorGaiva** [VictorGaiva/rabbit-stream#5]
# Overview
Tracking issue for adding support for the latest features of RabbitMQ Streams protocol (Route, Partitions and [Super Streams](https://blog.rabbitmq.com/posts/2022/07/rabbitmq-3-11-feature-preview-super-streams/))

## Description
This is intended to be the first version aimed at a wider usage.

## Objectives
- [x] Add the most recent features not yet supported (Partitions, SuperStreams, and others)
- [x] Improve the configuration
- [x] TLS Support (#6)
- [x] Improve the documentation
  - [x] Document all user facing modules and functions
- [x] Cover the main concepts on the Guides Docs:
  - [x] Consuming
  - [x] Producing
  - [x] Offset Tracking
  - [x] Credit Tracking
  - [x] TLS Usage
  - [x] Configuration
  - [x] SuperStreams: Consumer
  - [x] SuperStreams: Producer
  - [x] SuperStreams: Partitioning
  - [x] FilterValue
  - [x] Serialization
- [x] [Take an effort to spread the news on the community
](https://elixirforum.com/t/rabbitmq-streams-rabbitmq-streams-protocol-client/62425)

You can see the support table at [`docs/support-table.md`](https://github.com/VictorGaiva/rabbitmq-stream/blob/main/docs/support-table.md)
