### ISSUE TITLE
Version 0.5.0

### ISSUE THREAD

**Issue by VictorGaiva** [VictorGaiva/rabbit-stream#8]
# Overview

Tracking issue for expected features for 0.5.0, mainly aimed at advanced use cases.

## Objectives

- [ ] [WellBehaved CoonectionPool](https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/#well-behaved-clients)
  - [ ] Auto-discovery/Connection to multiple nodes of cluster
  - [ ] Loadbalanced commands
  - [ ] Attach Consumers and Producers to the best 'Connection', based on WellBehaved requirements
- [ ] Document examples
- [ ] Use NimbleOptions for validating configuration
- [ ] Aditional Offset Storage options (API for Storing on ETS?)
- [ ] Publish batching
- [ ] Consuming using Broadway
- [ ] Consuming and Producing(?) using GenStage
- [ ] Update OsirisChunk with the new [BloomFilter information](https://github.com/rabbitmq/rabbitmq-server/commit/75bf2a9ef5be6e1841f0b955b780541c5c6e4dd6)
